spring:
    profiles:
        active: local
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
andrew:
    thing: hello me
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
#                include: refresh, hystrix.stream, health, info