spring:
  kafka:
    bootstrap-servers:
      - docker-kafka:9092
  profiles:
    active: local
server:
  port: 8080
base:
  uri:
    server: http://docker-server
kafka:
    topic:
        refresh: refresh-config
management:
  endpoints:
    web:
      exposure:
        include: refresh, hystrix.stream
---

spring:
  profiles:
    active: dev