spring:
  kafka:
    bootstrap-servers:
      - docker-kafka:9092
  profiles:
    active: local
server:
  port: 7979
base:
  uri:
    server: http://docker-server
---

spring:
  profiles:
    active: dev