spring:
  kafka:
    bootstrap-servers:
      - docker-kafka:9092
  profiles:
    active: local
server:
  port: 8081
base:
  uri:
    server: http://docker-server
kafka:
    topic:
        refresh: refresh-config

---

spring:
  profiles:
    active: dev